#pragma once

#define WSASTARTUP_FAIL 1
#define ADDR_RESOLVE_FAIL 2
#define SOCKET_INIT_FAIL 3
#define CONNECTION_FAIL 4
#define DISCONNECTION_FAIL 5
#define SEND_FAIL -6
#define SEND_FAIL_INVALID_SIZE -7
#define RECV_FAIL -8